#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Pedros80\Build\Commands\BuildClasses;
use Pedros80\Build\Commands\GetStationData;
use Pedros80\Build\Commands\GetToken;
use Pedros80\Build\Commands\UpdateXmlFiles;
use Pedros80\Build\Commands\UpdateZipFiles;
use Pedros80\NREphp\Commands\PushPortListen;
use Pedros80\NREphp\Commands\RealTimeIncidentsListen;
use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommand(new BuildClasses());
$application->addCommand(new GetToken());
$application->addCommand(new UpdateXmlFiles());
$application->addCommand(new UpdateZipFiles());
$application->addCommand(new PushPortListen());
$application->addCommand(new RealTimeIncidentsListen());
$application->addCommand(new GetStationData());

$application->run();
